# Generated by Django 4.2.7 on 2023-11-27 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webDevApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('projectName', models.CharField(max_length=200)),
                ('projectOverview', models.CharField(max_length=500)),
                ('bannerImage', models.ImageField(upload_to='')),
                ('startDate', models.DateField(default='2024-01-01')),
                ('recruitingStatus', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('stage', models.CharField(max_length=200)),
                ('projectStatus', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
